/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const build_commitment_transaction: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint) => [number, number, number];
export const build_pending_proof: (a: number, b: number, c: number, d: number) => [number, number, number];
export const complete_proof: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const compute_sha256: (a: number, b: number) => [number, number];
export const compute_sha256_hex: (a: number, b: number) => [number, number];
export const create_commitment: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const create_submit_tx_rpc_request: (a: number, b: number) => [number, number, number, number];
export const generate_nonce: () => [number, number, number, number];
export const get_commitment_burn_amount: () => bigint;
export const get_version: () => [number, number];
export const get_wallet_address: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const get_wallet_info: (a: number, b: number, c: number, d: number) => [number, number, number];
export const is_valid_proof_format: (a: number, b: number) => number;
export const parse_proof: (a: number, b: number) => any;
export const serialize_proof_to_bytes: (a: any) => [number, number, number, number];
export const sign_transaction: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const validate_address: (a: number, b: number) => number;
export const validate_private_key: (a: number, b: number) => number;
export const verify_proof: (a: number, b: number, c: number, d: number) => any;
export const init: () => void;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
